### ISSUE TITLE
XMLHttpRequest error in Webversion und Exception in der App

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/Mensa-App#118]
![image](https://github.com/whosFritz/Mensa-App/assets/125283275/72d46d46-4715-479a-bf51-7c8bbac525c9)

Es erscheinen Fehlermeldungen beim aufrufen von Mensen

**Comment by whosFritz** [comment]
I got this error, know anything about this? @olech2412 

/#/:1 Access to XMLHttpRequest at 'https://api.olech2412.de/essensGetter/mealsForFritz/mensa_am_elsterbecken?code=I0SxorclyZZdctbCvBo6' from origin 'https://mensi-mates.whosfritz.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

main.dart.js:38423     GET https://api.olech2412.de/essensGetter/mealsForFritz/mensa_am_elsterbecken?code=I0SxorclyZZdctbCvBo6 net::ERR_FAILED 503 (Service Unavailable)

**Comment by LenMPorath** [comment]
Watn scheiß

Ole Einar Christoph ***@***.***> schrieb am Di., 6. Juni
2023, 10:52:

**Comment by olech2412** [comment]
:ant:
