### ISSUE TITLE
Berwetungs Issue

### ISSUE THREAD

**Issue by Schmiddyyy** [whosFritz/Mensa-App#34]
Ich möchte meine Bewertung im Nachhineinnochmal ändern können

**Comment by whosFritz** [comment]
Dear Schmiddyyy,

We at MensiApp by Fritz Schubert evaluate security and private data the highest. 
Your rating is beeing sent to our Data Center anonymous and enrypted. Therefore it's not possible for us to track your rating or ratings of any other individuals.
We might implement the feature to login into the app by google play sign in or by mail and password. After that we could implement the feature to change ur rating.
But at this time this kind of change goes against our company's rules.
Our CEO Fritz Schubert will think through these changes.

Thank you Mr. Schmiddyyy for your input


With kind Regards
Fritz Schubert
CEO of MensiApp
