### ISSUE TITLE
Windows build is broken

### ISSUE THREAD

**Issue by greybaron** [whosFritz/Mensa-App#40]
Error: `url_launcher_windows_plugin.dll` and `flutter_windows.dll` are missing

Possible solution: stop providing .exe builds 👍🏻

**Comment by whosFritz** [comment]
Dear Greybaron,

We at MensiApp by Fritz Schubert appreciate our cross-platform software and strive to develop a software solution for all target groups, including devices. We apologize that you have encountered problems when trying to improve our open-source application with your skills. Our developers are working day and night to ensure the stability of our applications on all platforms and thus promote possible collaboration by external developers. Please ensure that you have not made any errors when setting up the development environment and have followed the steps in the README.md: https://github.com/whosFritz/Mensa-App#readme and the documentation: https://github.com/whosFritz/Mensa-App/blob/master/essensgetterapp/dokumente/Documentation.md
If you continue to have problems, please contact our support.
(reachable by phone at 030 78 89 03 40. Calls from EU countries are free. Possible costs from outside the EU may occur.)


With kind regards
Fritz Schubert
CEO of MensiApp and Entrepreneur

![applogo512](https://user-images.githubusercontent.com/97552289/215052402-a7e60f7f-7f1e-4afd-8cb9-e20342aeaa8f.png)
